import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
fs.mkdirSync('tmp',{recursive:true});
await page.goto('http://127.0.0.1:4178');
await page.locator('h1').waitFor();await page.screenshot({path:'tmp/home-desktop.png',fullPage:true});
await page.getByRole('link',{name:'Start with the foundations'}).click();
await page.getByRole('heading',{name:'Meet the vessel',exact:true}).waitFor();
await page.getByRole('button',{name:'Mark lesson complete'}).click();await page.reload();
await page.getByRole('button',{name:'Completed · undo'}).waitFor();
await page.goto('http://127.0.0.1:4178/#/lesson/rsm-equation');
await page.getByText('Show full RSM model · Eqs. 1 / 21',{exact:true}).click();
assert.equal(await page.locator('.katex-error').count(),0);
await page.screenshot({path:'tmp/equation-desktop.png',fullPage:true});
await page.goto('http://127.0.0.1:4178/#/lesson/ch5-inverse');
const old=Number(await page.locator('.cost-grid strong').last().innerText());
await page.getByRole('button',{name:/Improve fit/}).click();
const next=Number(await page.locator('.cost-grid strong').last().innerText());assert.ok(next<=old);
await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'tmp/inverse-desktop.png',fullPage:true});
await page.getByText('My explanation · saved on this browser').click();await page.locator('#lesson-notes').fill('Every inverse iteration calls a forward model.');
await page.reload();await page.getByText('My explanation · saved on this browser').click();assert.equal(await page.locator('#lesson-notes').inputValue(),'Every inverse iteration calls a forward model.');
await page.goto('http://127.0.0.1:4178/#/quiz');
await page.locator('.quiz-card').first().getByRole('textbox').fill('Pressure loads a compliant wall.');
await page.locator('.quiz-card').first().getByRole('button',{name:'Show answer',exact:true}).click();
await page.locator('.quiz-card').first().getByRole('button',{name:'Can explain it',exact:true}).click();
await page.getByRole('button',{name:'COMSOL Ready',exact:true}).click();
await page.locator('.quiz-card').first().getByRole('button',{name:'Show answer',exact:true}).click();
assert.equal(await page.locator('.label-answer').count(),4);
await page.goto('http://127.0.0.1:4178/#/glossary');await page.getByRole('textbox',{name:'Search glossary'}).fill('transmural');assert.equal(await page.locator('.glossary-card').count(),1);
await page.goto('http://127.0.0.1:4178/#/sources');await page.getByRole('combobox').selectOption('rsm');assert.ok((await page.locator('.source-row').count())>0);
const pdf=await page.request.get('http://127.0.0.1:4178/sources/thesis.pdf');assert.equal(pdf.status(),200);
const links=await page.locator('a[href^="#/lesson/"]').evaluateAll(es=>es.map(e=>e.getAttribute('href')));assert.ok(links.length>0);
await page.goto('http://127.0.0.1:4178/#/home');await page.getByRole('button',{name:'Find a concept'}).click();await page.getByRole('textbox',{name:'Search learning app'}).fill('Nelder');assert.ok(await page.locator('.search-results a').count()>0);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').count(),0);
await page.getByRole('button',{name:'Switch to dark mode'}).click();await page.screenshot({path:'tmp/home-dark.png',fullPage:true});
await page.getByRole('button',{name:'Switch to light mode'}).click();
await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tmp/home-mobile.png',fullPage:true});
for(const path of ['home','lesson/ch5-inverse','lesson/rsm-equation','lesson/comsol-exercise','quiz','sources','glossary','lab']){
 await page.goto(`http://127.0.0.1:4178/#/${path}`);
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,`overflow ${path}`);
}
await page.goto('http://127.0.0.1:4178/#/lesson/comsol-exercise');await page.screenshot({path:'tmp/comsol-mobile.png',fullPage:true});
await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('link',{name:'Start here',exact:true}).click();
assert.equal(errors.length,0,errors.join('\n'));
fs.writeFileSync('tmp/browser-results.json',JSON.stringify({passed:true,consoleErrors:errors,checks:['navigation','progress persistence','notes persistence','KaTeX','inverse fit','quiz','diagram labels','glossary search','source filtering','PDF loading','search dialog','theme','responsive overflow','mobile navigation']},null,2));
console.log('Browser checks passed; screenshots saved under tmp/.');await browser.close();
