import { type Lesson, R, T } from './types';
export const bridge: Lesson[] = [
{id:'connect',group:'connect',title:'Two perturbations. One inverse idea.',subtitle:'See the shared structure without erasing the differences.',minutes:7,kind:'Interpretation',prerequisites:['rsm-idea','ch5-inverse'],diagram:'comparison',sections:[
{title:'The same question in different experiments',body:['RSM uses acoustic excitation and observes resonance plus dimensions, with an analytical shell relation and an iterative modulus estimate. Chapter 5 force-coupled ultrasound measures compression under probe force and fits a finite element deformation model.','Both recover an unobserved pressure through a model of mechanical response. But not every thesis technique uses the same inversion: venous collapse-force regressions and constrained waveform fits have their own assumptions.'],refs:[R(2,3),R(9),T(104,112),T(139,149)],kind:'Source reading'},
{title:'Different observations constrain different unknowns',body:['A dynamic response can add information about inertia and tension. A compression sweep provides changing geometry under known loading. Neither observation abolishes uncertainty in material properties or surrounding tissue.','This suggests a general research habit: write down what is supplied, what is observed, what is fitted, and what is assumed. Keep those four lists next to the model before interpreting a pressure output.'],kind:'Background concept'},
{title:'Why this thesis may have been sent to an RSM student',body:['Our interpretation: the thesis is a worked example of moving from simplified mechanics to a numerical model and fitting it to ultrasound observations. It makes the roles of geometry, materials, boundaries, and optimization tangible.','COMSOL could be used to test the RSM analytical assumptions before trying to build a more realistic inverse estimator. That is a possible research direction to discuss, not a claim about your professor’s intent.'],kind:'Interpretation'}
],takeaways:['Both methods perturb, observe, model, and infer.','Their excitations and physical models differ.','Use FEM to interrogate assumptions before adding complexity.'],recall:'Explain the connection between the papers in three sentences.',answer:'Both infer vessel pressure from an observable mechanical response. RSM uses acoustic resonance and an analytical shell model, while Chapter 5 fits FEM compression predictions to force-coupled ultrasound. The thesis suggests how realistic anatomy and material behaviour can complicate the assumptions underlying an inverse pressure estimate.'},
{id:'comsol-studies',group:'comsol',title:'What question are you asking COMSOL?',subtitle:'Stationary, eigenfrequency, and frequency-domain studies do different jobs.',minutes:7,kind:'Background concept',prerequisites:['fea','resonance'],diagram:'comsol',sections:[
{title:'Stationary: what shape balances these loads?',body:['A stationary mechanics study seeks an equilibrium under specified loads. For a pressurized artery, it can provide the deformed shape and stresses before small vibrations are considered. The fact that the numerical solver takes many steps does not make the result a physical time history.']},
{title:'Eigenfrequency: how can this loaded structure vibrate?',body:['An eigenfrequency study finds natural frequencies and mode shapes for the model. For a pressurized structure, vibration may need to be computed about its loaded equilibrium: prestress can change the effective stiffness.','COMSOL’s prestressed study combines an equilibrium calculation with a subsequent vibration analysis. Inspect which solution supplies the linearization state; do not assume a separate pressure solve is automatically connected to your vibration study.'],deeper:'A mode’s displayed displacement scale is generally arbitrary. Read the mode pattern and its frequency; do not interpret an exaggerated mode plot as the measured vibration amplitude of a vessel.'},
{title:'Frequency domain: how does it respond to this forcing?',body:['A frequency-domain analysis evaluates response to harmonic excitation across selected frequencies. It can show amplitude and phase at your observation location, given a specified load and damping.','A natural frequency and an observed response peak are related but not identical concepts. Excitation, damping, fluid loading, and where the response is measured affect which modes appear in the experiment.']}
],takeaways:['Stationary finds equilibrium.','Eigenfrequency finds natural vibration patterns.','Frequency domain predicts a response to specified harmonic forcing.'],recall:'Why might an eigenfrequency result alone fail to reproduce an experimental resonance curve?',answer:'It does not by itself specify the experimental forcing, damping, sensor location, or amplitude/phase response. Those affect the measured frequency-response curve.'},
{id:'comsol-exercise',group:'comsol',title:'Mini exercise · A pressurized tube in tissue',subtitle:'A hypothetical workflow for your first modelling discussion.',minutes:10,kind:'Educational workflow',prerequisites:['comsol-studies','connect'],diagram:'comsol-exercise',sections:[
{title:'Define a baseline you can understand',body:['1. Choose a simple arterial geometry and dimensional approximation. 2. Define radius and wall thickness with units and a clear loaded/unloaded reference. 3. Assign a wall material. 4. Add surrounding tissue or the simplified fluid environment needed for your baseline comparison.','5. Apply internal pressure with consistent external loading and supports. 6. Solve the stationary prestressed state if needed for the intended vibration analysis. Check equilibrium, displacement scale, and plausible geometry.'],deeper:'This is a possible educational workflow, not an assignment from your professor. Reproducing RSM requires respecting fluid inertia and the long thin-shell assumptions. A solid-only tube in an arbitrary tissue block is not automatically a reproduction of the analytical model.'},
{title:'Ask the dynamic question',body:['7. Choose prestressed eigenfrequency and/or harmonic frequency-response analysis for the research question. 8. Identify the intended mode by its shape, not just its order in a frequency list. 9. Sweep pressure. 10. Track how the corresponding mode and response change.','11. Vary radius, thickness, wall properties, and surrounding properties one at a time. 12. Compare the numerical trend with the RSM analytical relationship in a matched regime. Record any assumption changes with the results.']},
{title:'Before believing the colourful picture',body:['Repeat with a refined mesh and a larger surrounding domain. Compare the quantity you care about, such as midwall displacement or the matched-mode frequency, rather than judging colour alone.','Keep a simple lab record: geometry definition, parameter units, material law, constraints, load/study sequence, solver tolerance, mesh statistics, observation location, and validation target. If a solve fails, simplify and test the last successful model before interpreting a pressure estimate.'],confusion:'A failed or unconverged forward solve is not a physical observation. An inverse optimizer must handle it explicitly rather than treating arbitrary output as a good fit.'}
],takeaways:['Begin with a baseline whose assumptions match a reference.','Prestress, fluid/tissue loading, and mode identity matter.','Check mesh/domain sensitivity before studying anatomy.'],recall:'What would you record before showing a pressure–frequency curve to your professor?',answer:'Geometry and material assumptions, reference configuration, boundary conditions, load/prestress sequence, fluid/tissue representation, mode identity, units, convergence checks, and the analytical or experimental comparison.'}
];
