export const glossary: {term:string; definition:string; why:string; lesson:string}[] = [
['Lumen','The space inside a vessel that contains blood.','Segmentation usually traces the lumen boundary.','vessels'],
['Carotid','A major artery in the neck supplying the head.','The main arterial target in both readings.','vessels'],
['IJV','Internal jugular vein: a large vein returning blood from the head toward the heart.','Its compression is used to study venous pressure.','ch7'],
['CVP','Central venous pressure, associated with the large veins near the heart/right atrium.','The venous quantity estimated in Chapters 7–9.','ch7'],
['JVP','Jugular venous pulsation height, used for an indirect estimate of central venous pressure.','It is the noninvasive comparator in Chapter 7.','ch7'],
['GSV','Great saphenous vein, a superficial vein of the leg.','Chapter 6 studies its compressibility at different sites and postures.','ch6'],
['Systole','The contraction/ejection phase of the cardiac cycle.','Systolic arterial pressure is the high value within a beat.','vessels'],
['Diastole','The relaxation/filling phase between contractions.','Diastolic arterial pressure is the low value within a beat.','vessels'],
['Pulse pressure','Systolic pressure minus diastolic pressure.','It is one of the five Stage 1 unknowns in Chapter 5.','ch5-inverse'],
['Transmural pressure','Pressure inside a wall minus pressure outside it.','The difference affects vessel expansion and collapse.','vessels'],
['Force','A push or pull, measured in newtons.','A load cell measures probe force; pressure requires a mechanical interpretation.','mechanics'],
['Pressure','Normal force per unit area, measured in pascals or often mmHg for blood pressure.','Contact pressure and lumen pressure are not automatically equal.','mechanics'],
['Wall tension','Circumferential tensile force per unit axial length in a cylindrical wall.','Pressure contributes tension relevant to RSM resonance.','mechanics'],
['Young’s modulus','A material measure relating uniaxial stress and strain; for a linear elastic material it is constant.','A strain-dependent modulus lets the arterial response stiffen.','materials'],
['Poisson ratio','Negative lateral strain divided by longitudinal strain in a small uniaxial elastic test.','It influences volume change and multiaxial response.','materials'],
['Hyperelastic','An elastic material model whose stress derives from a strain-energy function.','Useful for large reversible tissue deformations.','materials'],
['Ogden model','A family of hyperelastic strain-energy models expressed using principal stretches.','Jaffe uses a modified prescription for surrounding tissue.','ch5-materials'],
['Stress','Internal force per unit area, including normal and shear components.','The FEM estimates how a load is carried inside tissue.','mechanics'],
['Strain','A dimensionless measure of deformation relative to a reference configuration.','It enters the arterial material law.','mechanics'],
['Displacement','Movement of a point from its reference position, with length units.','Its spatial variation produces strain.','fea'],
['Mesh','The connected partition of a model into finite elements.','It controls how a continuous field is approximated.','fea'],
['Element','A small region with a prescribed interpolation of unknown fields.','Elements assemble into one globally connected solution.','fea'],
['Boundary condition','A rule specifying behaviour or loading on the edge of a model.','Fixed, free, and loaded boundaries define the forward problem.','ch5-geometry'],
['Forward model','A calculation of response from supplied parameters and loading.','Every inverse iteration requires a forward prediction.','inverse'],
['Inverse mechanics problem','Using observed motion or deformation to estimate the hidden loads or properties that produced it.','This is the shared structure behind both research approaches.','inverse'],
['Inverse model','An estimation of unknown inputs from observed outputs under a model.','Pressure is hidden while deformation or resonance is observed.','inverse'],
['Cost function','A scalar score that quantifies disagreement and any penalties.','It defines what the optimizer tries to reduce.','inverse'],
['Optimization','A search for parameters that improve an objective score.','It adjusts candidate pressure and material parameters.','ch5-inverse'],
['Regularization','Additional penalties or constraints favouring plausible or stable solutions.','It can discourage implausible fits but also shape the answer.','ch5-inverse'],
['Identifiability','The extent to which observations distinguish different unknown parameters.','Pressure and stiffness can compensate for one another.','inverse'],
['Segmentation','Locating and tracing an object’s boundary in an image.','Radius and area depend on that boundary choice.','ultrasound'],
['B-mode','Ultrasound imaging that maps echo information into a brightness image of a slice.','It supplies vessel geometry for the studies.','ultrasound'],
['M-mode','Repeated ultrasound sampling along one line, displayed as depth versus time.','It supports faster carotid wall-motion tracking in Chapter 9.','ultrasound'],
['Eigenfrequency','A natural vibration frequency of the specified model and state.','A prestressed vessel can have different eigenfrequencies from an unloaded one.','comsol-studies'],
['Resonance','Enhanced forced response near a preferred vibration frequency.','RSM fits the stimulated arterial frequency response.','resonance'],
['Mode shape','The spatial pattern of displacement for a vibration mode.','The n = 2 mode approximately ovalizes the cross-section.','rsm-modes'],
['Prestress','Stress already present in the equilibrium state about which a further response is studied.','Internal pressure can change subsequent vibration behaviour.','comsol-studies'],
['Convergence','Meeting a numerical stopping or stabilization criterion.','Solver, mesh, and inverse convergence are different; none alone proves physical truth.','fea'],
['Collapse force','The first force at which segmented venous area falls below the chosen collapse threshold.','The thesis uses 0.5 mm² to define it.','ch6'],
['Shear-wave elastography','An approach that measures mechanical shear-wave propagation to infer stiffness under assumptions.','Compression-dependent shear speed motivates nonlinear tissue modelling.','ch6'],
['Nelder–Mead','A derivative-free optimizer that transforms a simplex of candidate parameter vectors.','MATLAB fminsearch uses it in the thesis inverse model.','ch5-inverse'],
['Vector Fitting','Fitting a measured frequency response using rational functions and their poles.','RSM uses it to estimate resonant frequency from magnitude and phase.','rsm-pipeline'],
['Hydrostatic pressure','The pressure contribution from the weight of a fluid column.','Posture changes the pressure relation between neck, heart, and legs.','ch6']
].map(([term,definition,why,lesson])=>({term,definition,why,lesson}));
