import { R, T, type Ref } from './types';
export type Recall = {id:string;level:'Foundation'|'Paper Understanding'|'COMSOL Ready';type:string;question:string;hint:string;answer:string;lesson:string;refs?:Ref[];labels?:{prompt:string;answer:string}[];choices?:{text:string;answer:string}[]};
export const recall:Recall[] = [
{id:'q1',level:'Foundation',type:'Explain in your own words',question:'Why does pressure push a vessel outward, and what prevents indefinite expansion?',hint:'Separate the fluid load from the wall’s response.',answer:'Pressure acts normally on the inner wall. Wall stresses and surrounding tissue support oppose it; the resulting shape is an equilibrium determined by material behaviour, geometry, and loading.',lesson:'vessels'},
{id:'q2',level:'Foundation',type:'Identify the error',question:'“My load cell reads 8 N, so the patient’s blood pressure is 8.” What is wrong?',hint:'Check units first, then the loading path.',answer:'Newtons measure force. Pressure is force per area, and even contact pressure is not lumen pressure. Force is transmitted through a nonuniform tissue stress field, so a mechanical model or validated estimator is required.',lesson:'mechanics'},
{id:'q3',level:'Foundation',type:'What happens if…',question:'You increase stiffness and pressure together. Could one compressed image still look almost unchanged?',hint:'Which parameter changes can compensate?',answer:'Yes. Greater pressure and changed stiffness can produce competing or compensating effects depending on the geometry/load. Multiple parameter combinations may fit one observation; use a load sweep or extra independent observations to improve identifiability.',lesson:'inverse'},
{id:'q4',level:'Foundation',type:'Diagram labelling',question:'Label the simplified vessel cross-section.',hint:'The central space contains blood; arrows represent a load.',answer:'A is the lumen; B is the vessel wall; C is the surrounding tissue; D indicates internal pressure acting normally on the wall.',lesson:'vessels',labels:[{prompt:'A · centre',answer:'Lumen'},{prompt:'B · ring',answer:'Vessel wall'},{prompt:'C · outside',answer:'Surrounding tissue'},{prompt:'D · arrows',answer:'Internal pressure'}]},
{id:'q5',level:'Foundation',type:'Classify the problem',question:'Which direction is each calculation going?',hint:'Ask whether the unknown is a response or an input.',answer:'Prediction from known loading is forward. Estimation of hidden loading from observed response is inverse.',lesson:'inverse',choices:[{text:'Pressure and stiffness → predicted vertical radius',answer:'Forward'},{text:'Observed vertical radius → estimated pressure',answer:'Inverse'},{text:'Known pressure and geometry → resonance frequency',answer:'Forward'},{text:'Measured resonance and dimensions → pressure',answer:'Inverse'}]},
{id:'q6',level:'Foundation',type:'Identify the error',question:'“Hyperelastic means very stiff, and elastic means the stress–strain graph is a straight line.”',hint:'Neither word specifies one constant slope.',answer:'Hyperelastic describes a strain-energy-based elastic material law. It can be very compliant or stiff. Elastic response can be nonlinear; a straight line is the extra assumption of linear elasticity.',lesson:'materials'},
{id:'q7',level:'Paper Understanding',type:'Paper-specific recall',question:'What extra information does RSM gain by stimulating the artery?',hint:'Passive radius tracking alone lacks an absolute pressure reference.',answer:'The stimulated mechanical frequency response reveals resonance. Together with dimensions and the physical model, this helps establish an absolute pressure estimate without a cuff-pressure input. Stiffness is estimated iteratively and other properties use assumptions.',lesson:'rsm-idea',refs:[R(2),R(9)]},
{id:'q8',level:'Paper Understanding',type:'Identify the error',question:'“The RSM error was −1.09 ± 1.98 mmHg in humans, proving clinical accuracy.”',hint:'Identify the experiment and the statistic.',answer:'That is signed mean error ± standard deviation in mock-up experiments. The human studies were early feasibility work: one subject at four sites and six carotid subjects with cuff comparisons, not definitive invasive clinical validation.',lesson:'rsm-evidence',refs:[R(3),R(10,11)]},
{id:'q9',level:'Paper Understanding',type:'Explain the pipeline',question:'Walk through Chapter 5 from raw recordings to a pressure waveform.',hint:'Name three processing steps before COMSOL and distinguish the two optimization stages.',answer:'Synchronize force and images, detect the carotid, segment deformation. Stage 1 repeatedly runs COMSOL to fit Pd, pulse pressure, E₀, α, and r₀ using force-sweep radii and penalties. Stage 2 fixes mechanics and fits lumen pressure per frame.',lesson:'ch5-inverse',refs:[T(100),T(108,112)]},
{id:'q10',level:'Paper Understanding',type:'What happens if…',question:'You turn off the 0.2 mm residual threshold in Chapter 5. What changes in the objective?',hint:'Consider small boundary shifts caused by segmentation.',answer:'The optimizer now tries to reduce discrepancies the original objective deliberately ignored as below the image uncertainty scale. It may spend computation or shift parameters to fit noise; this does not create more information.',lesson:'ch5-inverse',refs:[T(110,113)]},
{id:'q11',level:'Paper Understanding',type:'Evaluate evidence',question:'Why is Chapter 8’s ICU-fitted 1.08 mmHg error different evidence from its transferred MIT-model result?',hint:'Which data were used to choose the regression?',answer:'The ICU regression was fitted to the same small patient dataset used to report its error. The MIT-trained model was transferred to different data and had about 1.60 mmHg mean absolute error. In-sample fit and independent transfer answer different questions.',lesson:'ch8',refs:[T(161,164)]},
{id:'q12',level:'Paper Understanding',type:'Identify the error',question:'“Chapter 9 finished a 3D joint carotid–IJV model and independently validated all simultaneous waveforms.”',hint:'Check dimensionality and how the venous example was anchored.',answer:'The coupled Chapter 9 model is 2D; the earlier vein-only model is 3D. The venous waveform example uses MGH data with its mean fixed to invasive CVP and lacks precise synchronization. Stage-three IJV waveforms were not produced for the three simultaneous-study subjects.',lesson:'ch9',refs:[T(179,183)]},
{id:'q13',level:'COMSOL Ready',type:'Diagram labelling',question:'Label the Chapter 5 boundary conditions.',hint:'Think support, lateral motion, applied probe force, and lumen loading.',answer:'Bottom fixed; sides free; probe force on a top segment; blood pressure on the inner wall. Material interfaces connect the domains.',lesson:'ch5-geometry',refs:[T(105,107)],labels:[{prompt:'A · bottom',answer:'Fixed support'},{prompt:'B · sides',answer:'Free boundaries'},{prompt:'C · top segment',answer:'Probe force'},{prompt:'D · lumen boundary',answer:'Blood pressure'}]},
{id:'q14',level:'COMSOL Ready',type:'What happens if…',question:'You halve the mesh size and the artery’s predicted vertical radius changes substantially. Are you done?',hint:'Which type of convergence are you testing?',answer:'No. The quantity of interest is still sensitive to discretization. Refine appropriately, check element quality and model settings, and establish mesh convergence before interpreting that radius or fitting pressure.',lesson:'fea'},
{id:'q15',level:'COMSOL Ready',type:'Vocabulary in context',question:'Choose a study for each question: equilibrium shape, natural vibration patterns, and forced amplitude versus frequency.',hint:'Stationary / eigenfrequency / frequency domain.',answer:'Stationary → equilibrium shape. Eigenfrequency → natural frequencies and modes. Frequency domain → response to harmonic forcing. Use the appropriate prestressed state when pressure-induced equilibrium stress affects vibration.',lesson:'comsol-studies'},
{id:'q16',level:'COMSOL Ready',type:'Design a research test',question:'How would you use FEM to investigate an RSM assumption without changing everything at once?',hint:'Name a baseline, one change, a measured output, and a check.',answer:'Reproduce a simplified fluid-loaded shell with matching geometry/material assumptions; establish mesh/domain stability and identify n = 2. Change only surrounding elastic support, for example, then compare the matched mode and pressure inference with the analytical baseline.',lesson:'comsol-exercise'},
{id:'q17',level:'Paper Understanding',type:'Explain the mechanism',question:'Why might the IJV area shrink even if its own pressure has not decreased?',hint:'Think about the vessel next door.',answer:'Carotid expansion and surrounding tissue stresses can deform the IJV. A model omitting that interaction can misattribute an externally driven shape change to venous pressure.',lesson:'ch9',refs:[T(180,181)]},
{id:'q18',level:'COMSOL Ready',type:'Identify the error',question:'“The solver converged, so my material law is validated.”',hint:'Separate numerical solution from physical evidence.',answer:'Solver convergence means the chosen discretized equations satisfy a stopping criterion. Validation requires comparison with relevant independent physical observations. Mesh stability is another separate check.',lesson:'models'}
];
export const professorQuestions = ['Are we reproducing the RSM analytical assumptions in COMSOL first?','Will we model a phantom, a carotid artery, or both?','Are we studying eigenfrequencies, a forced frequency response, or both?','How will we represent blood and the surrounding tissue?','Which wall material law and reference configuration should we use?','Are we validating theory, designing a phantom, or investigating cases such as plaque?','What experimental measurements will validate the simulation?','Which model outputs and convergence checks should we record?'];
