import { type Lesson, R } from './types';
export const rsm: Lesson[] = [
{id:'rsm-idea',group:'rsm',title:'Listen to the tension',subtitle:'The RSM paper in one idea, then one layer deeper.',minutes:6,kind:'Source reading',prerequisites:['resonance','inverse'],diagram:'resonance',sections:[
{title:'The 30-second idea',body:['Pressure creates tension in an artery wall. That tension, the artery’s dimensions, its material properties, and surrounding fluid loading affect its mechanical resonance. Jimenez and colleagues acoustically excite the artery, use ultrasound to observe dimensions and wall motion, identify a resonant frequency, and invert a physical model to estimate pressure.'],refs:[R(2,3)]},
{title:'Why another blood-pressure method?',body:['The paper motivates continuous pressure waveforms because they carry information beyond the maximum and minimum of each beat. An arterial catheter provides invasive continuous monitoring; a conventional cuff gives intermittent measurements. Many cuffless approaches depend on repeated reference calibration.','RSM introduces an extra observable by actively perturbing the artery. Under its model, resonance supplies information missing from passive dimension tracking alone. “Calibration-free” here means the calculation does not take a cuff pressure as an input; it still relies on physical assumptions and estimated quantities.'],refs:[R(1,2),R(8,9)],confusion:'The paper describes a direct physical calculation and uses “without inference” in its significance statement. In the mathematical sense taught here, recovering pressure from measured response by inverting mechanics is still an inverse problem.'},
{title:'What changes from the guitar string?',body:['A string analogy explains the role of tension. The actual model is a long, thin, cylindrical shell with uniform radius and wall thickness, containing and surrounded by fluid. Fluid contributes inertia; the wall has elasticity and geometry that change with pressure.','The analysis concentrates on circumferential motion when the artery is long compared with its radius. This does not establish that every real artery behaves as an ideal shell in every circumstance.'],refs:[R(2),R(8,9)]}
],takeaways:['Acoustic excitation reveals resonance, an additional observable.','A mechanics equation connects response and dimensions to pressure.','Calibration-free does not mean assumption-free.'],recall:'Explain RSM without using the words “AI” or “black box.”',answer:'A physical shell model relates pressure to artery dimensions, stiffness, and resonant frequency. Ultrasound measures geometry and stimulated wall motion; the response is fitted and the relationship inverted for pressure.'},
{id:'rsm-equation',group:'rsm',title:'Read the equation as a physical story',subtitle:'What is measured, what is assumed, and what is inferred?',minutes:10,kind:'Source reading',prerequisites:['rsm-idea','materials'],diagram:'equation',sections:[
{title:'Start with the scaling',body:['In the paper’s thin-wall, small dimensionless-frequency regime, pressure has leading-order scaling with effective density × radius squared × resonant frequency squared. This is a proportionality for intuition, not a formula with a universal coefficient of one.','Holding all else fixed in that scaling, a 10% increase in frequency corresponds to a factor of 1.1² = 1.21 in the leading term. In a real heartbeat, radius and material response change too.'],refs:[R(2),R(9)],equation:String.raw`P\sim\rho a^2 f^2`,symbols:['P: inferred pressure (Pa).','ρ: model’s effective density (kg/m³), including wall and fluid contributions.','a: radius to the middle of the wall (m); f: fitted resonance frequency (Hz).'],confusion:'Do not insert lumen radius when the equation expects midwall radius. Do not turn a scaling relationship into a clinical calculator.'},
{title:'The full model is available when you are ready',body:['The explorer above shows Eq. 1 (repeated as Eq. 21), with its dimensionless thickness and frequency variables. Its form accounts for elasticity and thickness beyond the leading intuition. The shell assumptions remain essential.'],refs:[R(2),R(8,9)],deeper:'The leading approximation on p. 9 also contains a stiffness-related correction of order α³E. That is why saying “only frequency matters” misses part of the physical model.'},
{title:'Stiffness is part of a self-consistency loop',body:['The paper relates Young’s modulus to the pressure–radius slope. But the RSM pressure estimate itself depends on modulus. It chooses an initial modulus, calculates pressures, updates modulus from the pressure–radius relationship, and repeats using a Gauss–Seidel approach.','For human arteries, the method permits instantaneous stiffness variation. The mock-up analysis instead used an approximately constant modulus and compared it with an independent tensile measurement. These are different assumptions for different experiments.'],refs:[R(9,10)],equation:String.raw`E=\frac{a^2}{h}\frac{dP}{da}`,symbols:['E: estimated wall Young’s modulus (Pa); a: midwall radius (m); h: wall thickness (m).','dP/da: local change of pressure per change of radius (Pa/m).'],confusion:'E is not an independent stiffness measurement handed to RSM by B-mode imaging. It is estimated through coupled relationships. Density and Poisson ratio are assigned from prior information.'},
{title:'Thickness is not always directly resolved',body:['Human thickness handling uses imaging information and an incompressibility-based relation between thickness and radius. The thin mock-up walls were below adequate ultrasound thickness resolution, so caliper measurements of unpressurized geometry supplied the thickness calculation.','The mock-up analysis also describes radius adjustments and, for the larger tube, adding half the wall thickness to account for possible inner-wall rather than midwall echo localization. Read the validation with those processing choices in mind.'],refs:[R(9,11)]}
],takeaways:['a and f dominate the leading-order pressure scaling.','E is estimated iteratively; density and Poisson ratio use prior values.','The full equation and measurement definitions belong together.'],recall:'Which seven inputs enter the pressure relationship, and where do they come from?',answer:'a and h describe measured/derived geometry, f is fitted from the measured response, E is iteratively estimated, and ν, wall density ρS, and fluid density ρL use assumed prior properties.'},
{id:'rsm-modes',group:'rsm',title:'The n = 2 mode',subtitle:'The cross-section alternates between two flattened orientations.',minutes:5,kind:'Source reading',prerequisites:['resonance'],diagram:'mode',sections:[
{title:'A mode is a pattern of movement',body:['Different parts of a structure can move together in different patterns. A mode shape specifies one pattern; its frequency says how fast it oscillates in the model. In the circumferential n = 2 mode, the artery alternates between approximately horizontal and vertical oval shapes.','The drawing exaggerates movement and slows it down. It illustrates the circumferential component, not the full three-dimensional displacement field. n = 2 counts angular variation around the circumference, not the number of heartbeats or image frames.'],refs:[R(3),R(8)]},
{title:'Why focus on this mode?',body:['The paper argues that the lowest-frequency mode is generally easier to excite in a damped system and focuses on n = 2. It neglects terms associated with the small ratio of radius to vessel length in its long-cylinder limit.','The fluid moves along with the vibrating wall and contributes effective inertia. A vacuum shell’s frequency is therefore not the appropriate direct comparison for a blood-filled artery.'],refs:[R(8,9)],deeper:'The radial displacement basis includes an axial sine, an angular cosine cos(nθ), and an oscillation in time. The figure retains only the angular pattern. It should not be read as an exact area-preserving or anatomically realistic displacement solution.'}
],takeaways:['A mode shape is a spatial pattern, not a waveform of blood pressure.','n = 2 is an ovalizing circumferential mode.','Fluid loading matters when comparing frequencies.'],recall:'Why is an empty tube vibrating in air an incomplete RSM model?',answer:'The artery contains fluid and is mechanically loaded by its surroundings. Added inertia and support alter its response relative to a vacuum shell.'},
{id:'rsm-pipeline',group:'rsm',title:'From acoustic stimulus to a pressure trace',subtitle:'Follow the signal through the experiment.',minutes:7,kind:'Source reading',prerequisites:['ultrasound','rsm-equation'],sections:[
{title:'Excite and observe different physical signals',body:['Audio-frequency transducers provide the mechanical stimulus, while an ultrasound transducer images the vessel and measures top and bottom wall velocities. Their velocity difference highlights the circumferential wall response.','For static mock-up measurements, the stimulus sweeps frequencies. Human measurements use a repeating multifrequency waveform so multiple stimulus frequencies can be assessed over short intervals. The mechanical stimulation frequency is distinct from the ultrasound imaging carrier.'],refs:[R(3,4),R(9,11)]},
{title:'Fit a response, not just the tallest sampled point',body:['The measured frequency response includes both magnitude and phase relative to the stimulus. Vector Fitting approximates that response with rational functions and identifies a resonant pair of complex poles. The fitted poles supply the frequency estimate.','This permits peak localization more finely than the 10 Hz spacing of the mock-up sweep. Finer fitted resolution should not be confused with proven absolute accuracy of every estimate.'],refs:[R(3,4),R(9)],confusion:'A prominent peak alone is not all the evidence. The paper examines both magnitude and phase and uses a fitted dynamical response.'},
{title:'Assemble the pressure calculation',body:['Geometry tracking → wall-velocity response → resonance fitting → combined dimension estimates → iterative stiffness/pressure calculation → filtering and quality screening. The human pipeline uses a Kalman filter to combine motion and image-derived dimensions.','Manual probe or subject motion can spoil the data. The authors report signal loss as a regular occurrence and exclude unusable measurements. The various filter cutoffs described in the text and figures refer to processing choices; a fast raw output rate is not a guarantee of independent information at that rate.'],refs:[R(4),R(11)]}
],takeaways:['Mechanical stimulation and ultrasound imaging play separate roles.','Vector Fitting uses the complex frequency response.','Tracking, filtering, and data exclusions affect the final waveform.'],recall:'Where can motion create a false pressure change in this pipeline?',answer:'It can shift which boundaries are tracked, corrupt radius/thickness estimates or wall velocities, and contaminate the fitted response. These errors then enter the pressure calculation.'},
{id:'rsm-evidence',group:'rsm',title:'What the experiments establish',subtitle:'A controlled tube is not the same validation problem as a person.',minutes:8,kind:'Source reading',prerequisites:['rsm-pipeline'],sections:[
{title:'Mock artery: a controlled physical test',body:['Water-filled rubber tubing sat in a scattering fluid bath. A syringe set pressure and a transducer supplied a gauge reference. The authors tested two tube sizes over pressure ranges within 60–150 mmHg; the larger tube’s data above 130 mmHg were discarded because it expanded nonuniformly.','Resonant frequency increased with pressure. Across the reported mock-up measurements, model pressure minus gauge pressure had mean −1.09 mmHg and standard deviation 1.98 mmHg. This is signed mean error and scatter in vitro, not human accuracy or mean absolute error.'],refs:[R(3),R(10)]},
{title:'Human study 1: four sites, one person',body:['An author served as the subject in measurements of carotid, axillary, brachial, and femoral arteries. Resonance was observed and pressure waveforms were produced at all four sites, with intermittent cuff measurements for context.','This supports multi-site feasibility in one person. It does not establish population-wide artery independence or interchangeable systolic pressures across central and peripheral sites.'],refs:[R(4,6),R(10)]},
{title:'Human study 2: six carotid subjects',body:['The second feasibility study collected carotid data from six subjects and compared with brachial cuff measurements. The paper states that demonstrating observable human arterial resonance was the study’s aim, with subject numbers below a definitive standards-based validation.','The cuff is intermittent and at another arterial site. The black reference waveforms shown in the paper were constructed using a cuff-calibrated pressure–radius method; they are not invasive continuous ground truth.'],refs:[R(4,5),R(10,11)],confusion:'A nonsignificant difference in a small group is not proof of equivalence. Lower carotid systolic values can reflect site differences and/or RSM error; the paper acknowledges both.'}
],takeaways:['Mock-up results test the model in controlled conditions.','Human results establish early feasibility with small samples.','A calibrated reference waveform is not catheter validation.'],recall:'What experiment would strengthen the claim of accurate continuous human pressure?',answer:'A suitably designed larger study comparing time-aligned RSM output with an independent continuous reference, accounting for arterial site, motion, exclusions, and the pressure range.'},
{id:'rsm-limits',group:'rsm',title:'Where the elegant theory meets the body',subtitle:'Treat assumptions as testable research questions.',minutes:6,kind:'Source reading',prerequisites:['rsm-evidence'],sections:[
{title:'An artery is not a uniform shell in a fluid bath',body:['The paper recognizes multilayer, anisotropic artery walls embedded in tissue. The analytical model uses a long uniform shell and a simplified fluid environment. Dynamic stiffness estimation addresses nonlinear elasticity in part, but does not make every anatomical complication disappear.','Frequency and radius are leading contributors to the scaling. Radius estimation is singled out as an error source in the manually positioned, longitudinally aligned prototype. Smaller vessels challenge image contrast.'],refs:[R(3,4),R(7,9)]},
{title:'A slow oscillation has more than one explanation',body:['Longer pressure traces show slow variation that might relate to respiration. The authors also name handheld drift and limitations of the method as possible explanations. This remains tentative.','The proposed future catheter comparison would help distinguish genuine physiological variation from measurement/model errors. Sample size, site differences, and rejected motion-contaminated data constrain what the current human results establish.'],refs:[R(4,5),R(8),R(11)]},
{title:'Eight things to explain without the PDF',body:['1. The clinical need for a continuous waveform. 2. Why active excitation adds information. 3. The tension–resonance connection and its limits. 4. What a, h, f, E, ν, ρS, and ρL mean.','5. How the n = 2 response is measured and fitted. 6. Why stiffness and pressure are estimated together. 7. What mock-ups and each human study actually tested. 8. Why anatomy, geometry error, motion, and reference choice still matter.'],refs:[R(1,11)]}
],takeaways:['Real anatomy tests the shell assumptions.','Slow trace changes need independent confirmation.','The experiments justify further validation, not a claim of clinical equivalence.'],recall:'Name one RSM assumption you could test in a simulation and one measurement problem a simulation alone cannot fix.',answer:'You could test how nonuniform surrounding tissue shifts the n = 2 response. A simulation alone cannot determine the true boundary location in a noisy patient ultrasound image.'}
];
