import { sourceUrl } from '../lib/source-url';
import { useState } from 'react';
import katex from 'katex';
import { ArrowUpRight, BookOpen, Check, ChevronDown } from 'lucide-react';
import type { Ref, Section } from '../content/types';
import { glossary } from '../content/glossary';
export function SourceCitation({refs}:{refs:Ref[]}) {return <span className="citations">{refs.map((r,i)=><a key={i} href={sourceUrl(r.doc, r.page)} target="_blank" rel="noreferrer" title={`Open actual PDF page ${r.page}${r.end?`–${r.end}`:''}`}>[{r.doc==='rsm'?'RSM':'Thesis'} p. {r.page}{r.end?`–${r.end}`:''}]<ArrowUpRight size={10}/></a>)}</span>}
export function MathBlock({value}:{value:string}) {return <div className="math" dangerouslySetInnerHTML={{__html:katex.renderToString(value,{displayMode:true,throwOnError:false,strict:false,output:'htmlAndMathml'})}}/>}
export function GlossaryTooltip({term}:{term:string}) {const entry=glossary.find(g=>g.term.toLowerCase()===term.toLowerCase());const [open,setOpen]=useState(false);return <span className="glossary-inline"><button className="term" onClick={()=>setOpen(!open)} aria-expanded={open}>{term}</button>{open&&entry&&<span className="term-popover"><strong>{entry.term}</strong>{entry.definition}<a href={`#/lesson/${entry.lesson}`}>Learn the concept →</a></span>}</span>}
export function ConceptCard({section}:{section:Section}) {return <section className="concept-card"><div className="section-head"><h2>{section.title}</h2>{section.kind&&<span className="badge">{section.kind}</span>}</div>{section.body.map((p,i)=><p key={i}>{p}</p>)}{section.refs&&<SourceCitation refs={section.refs}/>}<div className="disclosures">{section.equation&&<details><summary><span>Show equation & physical meaning</span><ChevronDown size={16}/></summary><MathBlock value={section.equation}/><ul>{section.symbols?.map(s=><li key={s}>{s}</li>)}</ul></details>}{section.deeper&&<details><summary><span>Go deeper</span><ChevronDown size={16}/></summary><p>{section.deeper}</p></details>}{section.confusion&&<details className="confusion"><summary><span>Common confusion</span><ChevronDown size={16}/></summary><p>{section.confusion}</p></details>}</div></section>}
export function TakeawayBox({items,question,answer}:{items:string[];question:string;answer:string}) {return <section className="takeaway"><div className="eyebrow">BEFORE YOU MOVE ON</div><h2>Keep these three ideas.</h2><ul>{items.map(t=><li key={t}><Check size={17}/><span>{t}</span></li>)}</ul><details><summary><BookOpen size={17}/><span>Can you explain this? {question}</span></summary><p>{answer}</p></details></section>}
export function FigureShell({title,children,caption}:{title:string;children:React.ReactNode;caption?:string}) {return <section className="figure-shell"><div className="figure-top"><span className="eyebrow">EXPLORE THE IDEA</span><span className="badge">Conceptual visualization</span></div><h2>{title}</h2>{children}{caption&&<p className="figure-caption">{caption}</p>}</section>}
export function Slider({label,value,min,max,step=1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(n:number)=>void}) {return <label className="slider-label"><span>{label}<output>{Number(value.toFixed(2))} {unit}</output></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
